### ISSUE TITLE
pip error

### ISSUE THREAD

**Issue by lychees** [alphanemeless/VITS_TXT_to_Audio#2]
I try both python 3.10 and 3.11
```
PS D:\AI\Bot\VITS_TXT_to_Audio>  pip install  -r .\requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting pyopenjtalk
  Using cached https://mirrors.aliyun.com/pypi/packages/b4/80/a2505a37937fcd108b7c1ab66f7d1d48560525b1da71993860d11095a286/pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\25181\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\25181\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\25181\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_whe
el
          return hook(config_settings)
        File "C:\Users\25181\AppData\Local\Temp\pip-build-env-8s7jkqge\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\25181\AppData\Local\Temp\pip-build-env-8s7jkqge\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\25181\AppData\Local\Temp\pip-build-env-8s7jkqge\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\25181\AppData\Local\Temp\pip-build-env-8s7jkqge\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\25181\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\25181\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\25181\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by alphanemeless** [comment]
Just make sure that one of the two libraries, openjtalk and pyopenjtalk, is installed successfully. The installation of pyopenjtalk on some windows environments seems to have error
